// <auto-generated />
using System;
using MVC_DynamicMenu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_DynamicMenu.Migrations
{
    [DbContext(typeof(DynamicMenuDBContext))]
    [Migration("20210223115514_AddUserPermisionTable")]
    partial class AddUserPermisionTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_DynamicMenu.Models.UserPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MenuItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.ToTable("UserPermission");
                });

            modelBuilder.Entity("MVC_DynamicMenu.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserPermissionPermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserPermissionPermissionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MVC_DynamicMenu.Models.Users", b =>
                {
                    b.HasOne("MVC_DynamicMenu.Models.UserPermission", "UserPermission")
                        .WithMany("Users")
                        .HasForeignKey("UserPermissionPermissionId");
                });
#pragma warning restore 612, 618
        }
    }
}
