// <auto-generated />
using System;
using MVC_DynamicMenu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_DynamicMenu.Migrations
{
    [DbContext(typeof(DynamicMenuDBContext))]
    partial class DynamicMenuDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_DynamicMenu.Models.UserPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MenuItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserPermission");
                });

            modelBuilder.Entity("MVC_DynamicMenu.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MVC_DynamicMenu.Models.UserPermission", b =>
                {
                    b.HasOne("MVC_DynamicMenu.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersUserId");
                });

            modelBuilder.Entity("MVC_DynamicMenu.Models.Users", b =>
                {
                    b.HasOne("MVC_DynamicMenu.Models.Users", null)
                        .WithMany("UserPermission")
                        .HasForeignKey("UsersUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
